### ISSUE TITLE
Unable to run the docker container with the provided commands

### ISSUE THREAD

**Issue by dcarlus** [codec-abc/F--isomorphic-websocket-playground#1]
I take a clean copy of the repo and type the provided commands for building through Docker.
But I see some warnings/errors while building the Docker image (related to the Linux part).
Finally, I am unable to run it.

Here is the way I try to build the image. As you can see, I have a clean Docker as well (no image nor container at all before executing the commands). I have cutted off the build part as it was really slow even when accelerating 20 times the video (slow network).
https://youtu.be/C2lGVPFArd8

**Comment by codec-abc** [comment]
[see](https://github.com/docker/for-win/issues/2722).
